name: Deploy Unity WebGL



on:

  push:

    branches:

      - main



permissions:

  contents: read
  pages: write
  id-token: write



jobs:

  deploy:

    runs-on: ubuntu-latest



    steps:

      - name: Checkout

        uses: actions/checkout@v4
     
      - name: Setup Pages

        uses: actions/configure-pages@v6

      - name: Upload

        uses: actions/upload-pages-artifact@v3
        with:
          path: .
        
      - name: Deploy

        uses: actions/deploy-page@v4

        with:

          github_token:${{ secrets.GITHUB_TOKEN }}
          publish_dir:./deploy-pages@v4
